import Image from 'next/image'
import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import data from '/public/data.json'
import { documentToReactComponents } from '@contentful/rich-text-react-renderer'
import { Card, CardBody, Image as Img, Stack, Heading, Text, Flex } from '@chakra-ui/react'

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const { fields: { body, banner, title, footer, products }} = data;
  
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex as="main" className={`${styles.main} ${inter.className}`} gap="2rem" direction="column" align="center" justify="center">
        <Img 
          src={`https:${banner.fields.file.url}`}
          alt={banner.fields.title}
          width='100%'
          height='auto'
        />
        <Heading as="h1">{title}</Heading>

        { documentToReactComponents(body) }

        <Flex direction="row" wrap gap="2rem">
          {
            products.map( ({ sys: { id }, fields: { description, name, imei, image, tags } } ) => {
              return(
                <Card maxW='sm'>
                  <CardBody>
                    <Img
                      src={`https:${image.fields.file.url}`}
                      width='200'
                      height='250'
                      alt={image.fields.file.title}
                      borderRadius='lg'
                    />
                    <Stack mt='6' spacing='3'>
                      <Heading size='md'>{name}</Heading>
                      <Heading size='sm'>IMEI: {imei}</Heading>
                      <Text>
                        {description}
                      </Text>
                      <Flex direction="row" gap="1rem">
                        { tags.map( tag => {
                          return(
                              <Heading as="h2" size="sm" border="blue .1rem solid" padding=".5rem">{tag.fields.name}</Heading>
                          )})
                        
                        }
                      </Flex>
                    </Stack>
                  </CardBody>
                 
                </Card>
              )
            })


          }
        </Flex>
        <footer>
          <small>{footer}</small>
        </footer>
        


       
        
        {/* { products.map( ({ sys: { id }, fields: { description, name, imei, image, tags } }) => {
          return (
            <div key={id}>
              <div>{name}</div>
              <div>IMEI: {imei}</div>
              {
                description
              }
              
              <Image 
                src={`https:${image.fields.file.url}`}
                width='200'
                height='250'
                alt={image.fields.file.title}
              />
            </div>
          )})
        }
        <footer>
          <small>{footer}</small>
        </footer> */}
      </Flex>
    </>
  )
}
